language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t rahulzore/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahulzore/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-057567231716"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"